// <auto-generated />
using System;
using Gringotts.Api.Shared.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gringotts.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250127135024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gringotts.Api.Features.Client.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Gringotts.Api.Features.ClientAuthentication.Models.ClientSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagementUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManagementUserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ClientSecrets");
                });

            modelBuilder.Entity("Gringotts.Api.Features.Reader.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Gringotts.Api.Features.Reader.Models.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("Gringotts.Api.Features.Sessions.Models.ActiveSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LogReaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LogUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LogReaderId");

                    b.HasIndex("LogUserId");

                    b.ToTable("ActiveSessions");
                });

            modelBuilder.Entity("Gringotts.Api.Features.Sessions.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LogReaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LogUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LogReaderId");

                    b.HasIndex("LogUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Gringotts.Api.Features.Sessions.Models.SessionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LogReaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LogUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("LogReaderId");

                    b.HasIndex("LogUserId");

                    b.ToTable("SessionLogs");
                });

            modelBuilder.Entity("Gringotts.Api.Features.Statistics.Models.ReaderAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReaderId")
                        .IsUnique();

                    b.ToTable("LogReaderAnalyticsSet");
                });

            modelBuilder.Entity("Gringotts.Api.Features.Statistics.Models.UserAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LogUserAnalyticsSet");
                });

            modelBuilder.Entity("Gringotts.Api.Features.User.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Gringotts.Api.Features.User.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Affiliation")
                        .HasColumnType("smallint");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Sex")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("LogUsers");
                });

            modelBuilder.Entity("Gringotts.Api.Features.ClientAuthentication.Models.ClientSecret", b =>
                {
                    b.HasOne("Gringotts.Api.Features.Client.Models.Client", null)
                        .WithOne()
                        .HasForeignKey("Gringotts.Api.Features.ClientAuthentication.Models.ClientSecret", "ManagementUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gringotts.Api.Features.Reader.Models.Reader", b =>
                {
                    b.HasOne("Gringotts.Api.Features.Reader.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("Gringotts.Api.Features.Sessions.Models.ActiveSession", b =>
                {
                    b.HasOne("Gringotts.Api.Features.Reader.Models.Reader", null)
                        .WithMany()
                        .HasForeignKey("LogReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gringotts.Api.Features.User.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LogUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gringotts.Api.Features.Sessions.Models.Session", b =>
                {
                    b.HasOne("Gringotts.Api.Features.Reader.Models.Reader", null)
                        .WithMany()
                        .HasForeignKey("LogReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gringotts.Api.Features.User.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LogUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gringotts.Api.Features.Sessions.Models.SessionLog", b =>
                {
                    b.HasOne("Gringotts.Api.Features.Reader.Models.Reader", null)
                        .WithMany()
                        .HasForeignKey("LogReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gringotts.Api.Features.User.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LogUserId");
                });

            modelBuilder.Entity("Gringotts.Api.Features.Statistics.Models.ReaderAnalytics", b =>
                {
                    b.HasOne("Gringotts.Api.Features.Reader.Models.Reader", null)
                        .WithOne()
                        .HasForeignKey("Gringotts.Api.Features.Statistics.Models.ReaderAnalytics", "ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gringotts.Api.Features.Statistics.Models.UserAnalytics", b =>
                {
                    b.HasOne("Gringotts.Api.Features.User.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Gringotts.Api.Features.Statistics.Models.UserAnalytics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gringotts.Api.Features.User.Models.User", b =>
                {
                    b.HasOne("Gringotts.Api.Features.User.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
